export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const TOGGLE_PLAYING = 'TOGGLE_PLAYING';
export const SET_CURRENT_PLAYLIST = 'SET_CURRENT_PLAYLIST';
export const SET_CATEGORIES_PLAYLIST = 'SET_CATEGORIES_PLAYLIST';
export const GET_TOP_TEN_PLAYLIST = 'GET_TOP_TEN_PLAYLIST';
export const GET_RANDOM_ARTIST_LIST = 'GET_RANDOM_ARTIST_LIST';
export const GET_COVER = 'GET_COVER';
export const ADD_PLAYLIST_TO_LIBRARY = 'ADD_PLAYLIST_TO_LIBRARY';
export const ADD_SONG_TO_LIBRARY = 'ADD_SONG_TO_LIBRARY';
export const FIND_PLAYLIST_FROM_LIBRARY = 'FIND_PLAYLIST_FROM_LIBRARY';
export const FIND_SONGS_FROM_LIBRARY = 'FIND_SONGS_FROM_LIBRARY';
export const CLEAR_CURRENT_PLAYLIST_LIBRARY = 'CLEAR_CURRENT_PLAYLIST_LIBRARY';
export const REMOVE_SONG_LIBRARY = 'REMOVE_SONG_LIBRARY';
export const FIND_PLAYLIST_ARRAY_FROM_LIBRARY =
  'FIND_PLAYLIST_ARRAY_FROM_LIBRARY';
