export const SET_CURRENT_SONG = 'SET_CURRENT_SONG';
export const TOGGLE_PLAYING = 'TOGGLE_PLAYING';
export const SET_CURRENT_PLAYLIST = 'SET_CURRENT_PLAYLIST';
export const SET_CATEGORIES_PLAYLIST = 'SET_CATEGORIES_PLAYLIST';
export const GET_TOP_TEN_PLAYLIST = 'GET_TOP_TEN_PLAYLIST';
export const GET_RANDOM_ARTIST_LIST = 'GET_RANDOM_ARTIST_LIST';
export const GET_COVER = 'GET_COVER';
